### ISSUE TITLE
archiveurl for perlft link

### ISSUE THREAD

**Issue by Jimw338** [lorenzo-stoakes/weak#1]
http://web.archive.org/web/20180831082405/http://chessprogramming.wikispaces.com/perft

**Comment by Evangelos-Dimos** [comment]
how can I contribute?

**Comment by ljskernel** [comment]
@Evangelos-Dimos This project is dead as a doorknob (look at last commit time :) so no contribs will be accepted at this point, however you are more than welcome to fork this and work on it on your own, I licensed it under GPLv3 for some reason (rather than GPLv2) so you are completely free to use it on that basis for whatever purposes you prefer.

Cheers!

Also I know it's like 3 1/2 years late (oops!) but thanks @Jimw338 for the link.
